# Generated by Django 2.1.7 on 2019-03-09 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintainance_requests', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintainancerequest',
            name='author',
        ),
    ]
